export const FETCH_PERMINTAAN_HARGA = 'FETCH_PERMINTAAN_HARGA';
export const FETCH_MEDIA_IKLAN = 'FETCH_MEDIA_IKLAN';

export const FETCH_QTY_BALIHO = 'FETCH_QTY_BALIHO';
export const FETCH_QTY_MITRA = 'FETCH_QTY_MITRA';
export const FETCH_QTY_ADVERTISER = 'FETCH_QTY_ADVERTISER';

export const PREPARE_MOUNT = 'PREPARE_MOUNT';
export const ON_MOUNTED = 'ON_MOUNTED';
export const PREPARE_SEARCH = 'PREPARE_SEARCH';
export const AFTER_SEARCH = 'AFTER_SEARCH';
export const ON_UNMOUNT = 'ON_UNMOUNT'; 

export const FETCH_MITRA = 'FETCH_MITRA';
export const FETCH_ADVERTISER = 'FETCH_ADVERTISER';
